export const GENERATE_EXCEL_LOADING_KEY = 'GENERATE_EXCEL_LOADING_KEY'
export const CONTROLS_SECONDARY_LIST_LOADING_KEY = 'CONTROLS_SECONDARY_LIST_LOADING_KEY'
export const CONTROLS_TABLE_LOADING_KEY = 'CONTROLS_TABLE_LOADING_KEY'

export const SEARCH_RESULT_LOADING_KEY = 'SEARCH_RESULT_LOADING_KEY'

export const LEGAL_ENTITIES_TABLE_LOADING_KEY = 'LEGAL_ENTITIES_TABLE_LOADING_KEY'

export const INDIVIDUAL_ENTITIES_TABLE_LOADING_KEY = 'INDIVIDUAL_ENTITIES_TABLE_LOADING_KEY'

export const ENTITIES_TABLE_LOADING_KEY = 'ENTITIES_TABLE_LOADING_KEY'

export const PARTICIPATIONS_TABLE_LOADING_KEY = 'PARTICIPATIONS_TABLE_LOADING_KEY'

export const COUNTRIES_SELECT_LOADING_KEY = 'COUNTRIES_SELECT_LOADING_KEY'

export const JOB_TITLES_SELECT_LOADING_KEY = 'JOB_TITLES_SELECT_LOADING_KEY'

export const GLOBAL_FORM_SUBMIT_LOADING_KEY = 'GLOBAL_FORM_SUBMIT_LOADING_KEY'
