export const getDefaultClassName = (props, mainName) => {
  let classNames = mainName ? [mainName] : []

  if(props.hidden === true) classNames.push('hidden')
  if(props.transparent === true) classNames.push('transparent')
  if(props.small === true) classNames.push('small')
  if(props.big === true) classNames.push('big')
  if(props.large === true) classNames.push('large')
  if(props.dark === true) classNames.push('dark')
  if(props.light === true) classNames.push('light')
  if(props.tiny === true) classNames.push('tiny')
  if(props.active === true) classNames.push('active')
  if(props.primary === true) classNames.push('primary')
  if(props.main === true) classNames.push('main')
  if(props.white === true) classNames.push('white')
  if(props.grey === true) classNames.push('grey')
  if(props.lightGrey === true) classNames.push('light-grey')
  if(props.red === true) classNames.push('red')
  if(props.yellow === true) classNames.push('yellow')
  if(props.green === true) classNames.push('green')
  if(props.blue === true) classNames.push('blue')
  if(props.darker === true) classNames.push('darker')
  if(props.color) classNames.push(props.color)
  if(props.borderTop === true) classNames.push('border-top')
  if(props.borderLeft === true) classNames.push('border-left')
  if(props.basicPadding === true) classNames.push('basic-padding')
  if(props.basicPaddingRight === true) classNames.push('basic-padding-right')
  if(props.smallWidth === true) classNames.push('small-width')
  if(props.centerChild === true) classNames.push('center-child')
  if(props.largePadding === true) classNames.push('large-padding')
  if(props.smallPadding === true) classNames.push('small-padding')
  if(props.noPadding === true) classNames.push('no-padding')
  if(props.noBorder === true) classNames.push('no-border')
  if(props.noBorderTop === true) classNames.push('no-border-top')
  if(props.largeMargin === true) classNames.push('large-margin')
  if(props.smallMargin === true) classNames.push('small-margin')
  if(props.noMargin === true) classNames.push('no-margin')
  if(props.textRight === true) classNames.push('text-right')
  if(props.textLeft === true) classNames.push('text-left')
  if(props.textCenter === true) classNames.push('text-center')
  if(props.fullWidth === true) classNames.push('full-width')
  if(props.empty === true) classNames.push('empty')
  if(props.stretch === true) classNames.push('stretch')
  if(props.scroll === true) classNames.push('scroll')
  if(props.flexDirection) classNames.push('flec-direction-' + props.flexDirection)
  if(props.flex) classNames.push('flex-' + props.flex)

  return classNames.join(' ')
}
